version: '3.8'

services:
  mongo:
    image: mongo:latest
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    ports:
      - '27017:27017'
    volumes:
      - mongo-data:/data/db
    healthcheck:
      test: "echo 'db.runCommand({ ping: 1 })' | mongo --quiet --eval 'db.runCommand({ ping: 1 })'"
      interval: 10s
      timeout: 10s
      retries: 5

  nestjs:
    build:
      context: .
      dockerfile: Dockerfile # ระบุ Dockerfile ที่สร้างใน root directory
    restart: always
    depends_on:
      mongo:
        condition: service_healthy
    ports:
      - '3000:3000'
    environment:
      MONGO_URI: 'mongodb://root:example@mongo:27017/my-nest-starter-mongo-1?authSource=admin'
    volumes:
      - .:/app # เพื่อให้สามารถทำงานร่วมกับไฟล์ในโฟลเดอร์โปรเจคได้

volumes:
  mongo-data:
    driver: local
